version: '3'

volumes:
  mysql-db:
    driver: local
  es-data:
    driver: local

services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/etc:/etc/mysql/conf.d
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=laravel_elasticsearch
      - MYSQL_ROOT_PASSWORD=password01

  ## composer installs
  composer:
    build: ./
    command: composer install -d /projects/laravel/laravel_elasticsearch/server
    volumes:
      - ${PROJECT_FILE_PATH}:/projects/laravel/laravel_elasticsearch:cached
    links:
      - mysql

  ## app services
  laravel:
    build: ./
    command: php /projects/laravel/laravel_elasticsearch/server/artisan serve --host 0.0.0.0 --port=9000
    volumes:
      - ${PROJECT_FILE_PATH}:/projects/laravel/laravel_elasticsearch:cached
    depends_on:
      - composer
    restart: always
    ports:
      - 9000:9000
    links:
      - mysql


  elasticsearch:
    image: elasticsearch:7.3.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
